name: Release Packages

on:
  push:
    tags:
      - "v*.*.*" # Trigger the workflow when a new tag is pushed (e.g., v1.0.0)

jobs:
  # Existing Debian Packaging Workflow
  debian-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper bazel

      - name: Build Debian package
        run: |
          chmod +x ./build.sh
          ./build.sh
          dpkg-buildpackage -us -uc

      - name: Upload Debian Package to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ./path-to-debian-package/*.deb

  # New Fedora Packaging Workflow
  fedora-build:
    runs-on: fedora-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo dnf update -y
          sudo dnf install -y rpm-build gcc make bazel

      - name: Build using build.sh
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Package RPM
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cp ./fedora/stone-prover.spec ~/rpmbuild/SPECS/
          rpmbuild -ba ~/rpmbuild/SPECS/stone-prover.spec \
            --define "_topdir $HOME/rpmbuild" \
            --define "version ${GITHUB_REF#refs/tags/}" \
            --define "arch x86_64"

      - name: Verify RPM
        run: ls -la ~/rpmbuild/RPMS/x86_64/

      - name: Upload RPM to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ~/rpmbuild/RPMS/x86_64/*.rpm
